on:
  push:
    branches:
      - master

permissions:
  actions: write

jobs:
  build:
    name: "Build Python executable"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'macos-latest' ]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install wheel
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller main.spec
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/moodle_scraper*
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.4
        with:
          age: '1 day'
          skip-recent: 4