on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build Python executable"

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'macos-latest' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install wheel
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller main.spec
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: |
            dist/main.exe
            dist/moodle_scraper.app
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'
          skip-recent: 5